### ISSUE TITLE
Is there any option to rename property ?

### ISSUE THREAD

**Issue by ball6847** [slaveofcode/podeng#2]
I have just came across `jkt` and like it so much.
Then I notice `podeng` from README and follow it here.

One of features I like the most in `jkt` is, it can rename property on the fly, so I'm just wondering, Is it able to rename property like `jkt` can ?

Thanks for great libraries.

**Comment by slaveofcode** [comment]
hi @ball6847 it is great to know you using `jkt` before you left here, sure the concept of renaming property was different on `podeng`, in `podeng` they called serialize and deserialize to change the property on the fly, let me explain it a bit. 

Serialize is like changing from the original context of properties into another shape of properties, and deserialize is the same but has a reversed style of it (serializing).

## Serialize Example:
So if you have a schema with props like this

    const Person =  blueprint.object({
      name: types.string({ serialize: { to: 'person_name' }})
    })

    // prop name not changed
    console.log(Person({ name: "John Doe" })) // {"name": "John Doe"}

    // prop name changed
    console.log(Person.serialize({ name: "John Doe" })) // {"person_name": "John Doe"}

## Deserialize Example:

    const Person =  blueprint.object({
      name: types.string({ deserialize: { from: 'person_name' }})
    })

    // prop name not changed
    console.log(Person({ name: "John Doe" })) // {"name": "John Doe"}

    // prop name changed
    console.log(Person.deserialize({ person_name: "John Doe" })) // {"name": "John Doe"}

You could use the serialize or deserialize options (or both) depending on what you needs, those options available across many types with the same pattern.

For more info about available options see [Types options](https://github.com/slaveofcode/podeng#types-options).

There are so many options and feature more than you can see on the readme, just going through the test codes to capture any samples and the idea behind.
